### ISSUE TITLE
How to enable Account for storlets?

### ISSUE THREAD

**Issue by Daqu** [JosepSampe/micro-controllers#1]
when i try `swift download data test.json -H "X-Run-Storlet:noop-1.0.jar"`. i get below result:
```
Error downloading object 'data/test.json': Object GET failed: http://139.180.207.22:8080/v1/AUTH_d3c8edd651c74e81a14ea0f6943f19f3/data/test.json 400 Bad Request   Account disabled for storlets
```

i found it that this logger function located in `Engine/swift/vertigo_middleware/handlers/base.py`
and its default value is *False*.

i try below command:
```
swift download data test.json -H "X-Run-Storlet:noop-1.0.jar" -H "X-Account-Sysmeta-storlets_enabled: True"
```
but it doesn't work! hope for your help,sir.

PS:Why the `storlets` cannot show that `installed in pip list` is installed after installation.after i type `pip install storlets`.it works.

**Comment by JosepSampe** [comment]
Hi @Daqu, You must enable storlets execution to the desired tenant by: 
`swift post -H "X-account-meta-storlet-enabled:True"`

**Comment by Daqu** [comment]
done!
